name: Tes Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"

      - name: Install NPM dependencies
        run: npm install

      # Jika ada proses build frontend (misal Vite, Mix), aktifkan baris di bawah ini:
      - name: Build frontend
        run: npm run build

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, zip, curl, gd, mysql

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Run Laravel Artisan commands
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      # Deploy ke public_html
      - name: Deploy to public_html with rsync
        run: |
          rsync -av --delete ${{ github.workspace }}/ /home/jogjacare.my.id/public_html/
