name: CI

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /home/jogjacare.my.id/public_html/
    steps:
        - uses: actions/checkout@v2
