name: CI

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Go to directory
        run: cd /home/jogjacare.my.id/public_html/
      - uses: actions/checkout@v2
